from colorama import Fore, init

init()

INPUT_COLOR = Fore.CYAN
ERROR_COLOR = Fore.RED
SUCCESS_COLOR = Fore.BLUE
HIGHLIGHT_COLOR = Fore.MAGENTA
GOLD_COLOR = Fore.YELLOW
PLAIN_HIGHLIGHT_COLOR = Fore.LIGHTWHITE_EX
SCORE_COLOR = Fore.LIGHTGREEN_EX

# PODIUM_COLOR = Fore.YELLOW